Добавление бронирования, отзывов и БД
NastasyaRosh/java-shareit pull request #2
Opened 2023-05-10 12:30 UTC by NastasyaRosh

-refactor User и Item оформлены через БД
-feat Добавлена функция бронирования (Booking)
-feat Добавлена функция отзывов (Comment)

2023-05-11 03:01 UTC, sergeymamonov requested changes
ItemRequestDto, ItemRequest, UserDto - посмотрите, возможно ли заменить конструктор на @AllArgsConstructor.

2023-05-11 03:01 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
Лучше сделать ветку default на случай получения неподдерживаемого статуса.

2023-05-11 03:01 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        User booker = userService.findById(userId);
Всю эту логику (вызов одного сервисного метода, потом другого) я бы перенес в сервис. А здесь оставил только один вызов метода из сервиса. Чтобы в контроллере не было никакой логики (вызов цепочки методов - это тоже логика).

2023-05-11 03:01 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        State bookingState = State.checkState(state);
Валидацию лучше перенести в сервис.

2023-05-11 03:01 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/dto/InItemDto.java
> +    public InItemDto(Long id, String name, String description, Boolean available) {
А здесь с @AllArgsConstructor не получалось?

2023-05-11 03:01 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +    /*@ManyToOne
Не нужно оставлять закомментированного кода.

2023-05-11 06:16 UTC, NastasyaRosh commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
У нас просто получается уже этого есть проверка State.checkState(state), поэтому не стала изначально делать тут дефолт, но добавила на всякий.

2023-05-11 06:31 UTC, NastasyaRosh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        User booker = userService.findById(userId);
А как в целом лучше - передавать в сервис дто и там уже в сущность переводить или в сервис уже передавать сущность?

2023-05-12 03:21 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/service/BookingService.java
> +        }
Да, всегда остается вероятность, что когда будут дальше работать над кодом, то сломают в каком-то месте и всегда нужно делать проверки в коде, чтобы на каждом этапе проверять, работам ли мы сейчас с валидными данными. Но этим тоже не нужно злоупотреблять, так как лишние проверки замедляют код и увеличивают объем кода. Но default как раз им лучше не пренебрегать.

2023-05-12 03:34 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        User booker = userService.findById(userId);
В сервис нужно передавать доменные объекты. Домен (сервис) не должен ничего знать про инфраструктурные объекты. Таким образом у домена не будет зависимостей от инфраструктурных компонентов. Насколько понимаю то, что вы имели в виду в вашем вопросе, то "в сервис уже передавать сущность"

2023-05-12 03:35 UTC, sergeymamonov approved these changes

2023-05-12 08:42 UTC, NastasyaRosh commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +        User booker = userService.findById(userId);
@sergeymamonov Спасибо за ответ! :)

2023-05-12 08:43 UTC, merged